import type { VercelRequest, VercelResponse } from '../_types';
import { neon } from '@neondatabase/serverless';
import { existsSync, mkdirSync } from 'fs';
import { execFile } from 'child_process';
import { promisify } from 'util';
import path from 'path';

const execFileAsync = promisify(execFile);
const SNAPSHOTS_DIR = path.join(process.cwd(), 'snapshots');
const CHROMIUM_VERSION = '148.0.0';
const CHROMIUM_ARCH = process.arch === 'arm64' ? 'arm64' : 'x64';
const CHROMIUM_URL =
  process.env['CHROMIUM_DOWNLOAD_URL'] ??
  `https://github.com/Sparticuz/chromium/releases/download/v${CHROMIUM_VERSION}/chromium-v${CHROMIUM_VERSION}-pack.${CHROMIUM_ARCH}.tar`;

async function capturePageHTML(pageUrl: string): Promise<string> {
  const chromium = (await import('@sparticuz/chromium-min')).default;
  const { chromium: pw } = await import('playwright-core');

  const browser = await pw.launch({
    args: [
      ...chromium.args,
      '--disable-blink-features=AutomationControlled',
      '--disable-features=IsolateOrigins,site-per-process',
      '--flag-switches-begin',
      '--disable-site-isolation-trials',
      '--flag-switches-end',
    ],
    executablePath: await chromium.executablePath(CHROMIUM_URL),
    headless: true,
  });

  try {
    const context = await browser.newContext({
      userAgent:
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
      viewport: { width: 1920, height: 1080 },
      locale: 'pt-PT',
      extraHTTPHeaders: {
        Accept:
          'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        'Accept-Language': 'pt-PT,pt;q=0.9,en;q=0.8',
        'Accept-Encoding': 'gzip, deflate, br',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'none',
        'Sec-Fetch-User': '?1',
      },
    });

    await context.addInitScript(() => {
      Object.defineProperty(navigator, 'webdriver', { get: () => false });
      Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3] });
      Object.defineProperty(navigator, 'languages', { get: () => ['pt-PT', 'pt', 'en'] });
      // @ts-ignore
      window.chrome = { runtime: {} };
    });

    const page = await context.newPage();

    const resourceCache = new Map<string, { body: Buffer; type: string }>();
    await page.route('**/*', async (route) => {
      try {
        const response = await route.fetch();
        const body = await response.body();
        const type = response.headers()['content-type'] ?? 'application/octet-stream';
        resourceCache.set(route.request().url(), { body, type });
        await route.fulfill({ response });
      } catch {
        await route.abort();
      }
    });

    await page.goto(pageUrl, { waitUntil: 'networkidle', timeout: 60_000 });

    const blocked = await page.evaluate(() => {
      const text = document.body?.innerText ?? '';
      const title = document.title ?? '';
      return (
        text.includes('Request blocked') ||
        text.includes('Generated by cloudfront') ||
        title.toLowerCase().includes('access denied') ||
        title.toLowerCase().includes('403')
      );
    });
    if (blocked)
      throw new Error('Bot-wall detected: the listing site blocked the headless browser');

    try {
      const showMore = page.locator('button:has-text("Mostrar mais")').first();
      await showMore.waitFor({ state: 'visible', timeout: 5000 });
      await showMore.click();
      await page.waitForTimeout(500);
    } catch {
      // button may not exist on all listings
    }

    await page.evaluate(() => {
      document.querySelectorAll('script, noscript, laq-survey-root').forEach((el) => el.remove());
    });

    let html = await page.content();

    // Inline images, CSS and fonts only (no JS — avoids 100MB bloat and mangling)
    for (const [url, { body, type }] of resourceCache) {
      const baseType = type.split(';')[0];
      if (
        !baseType.startsWith('image/') &&
        !baseType.startsWith('text/css') &&
        !baseType.startsWith('font/')
      )
        continue;
      const dataUri = `data:${baseType};base64,${body.toString('base64')}`;
      const escaped = url.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      html = html.replace(new RegExp(escaped, 'g'), dataUri);
    }

    html = html.replace(/<script\b[^>]*\ssrc=["'][^"']*["'][^>]*>\s*<\/script>/gi, '');

    const lightbox = `
<style>
#__lb{display:none;position:fixed;inset:0;background:rgba(0,0,0,.92);z-index:2147483647;align-items:center;justify-content:center;flex-direction:column}
#__lb.open{display:flex}
#__lb-img{max-width:92vw;max-height:85vh;object-fit:contain;border-radius:4px}
#__lb-bar{display:flex;align-items:center;gap:16px;margin-top:12px}
.lb-btn{background:rgba(255,255,255,.15);border:none;color:#fff;font-size:1.4rem;padding:6px 18px;cursor:pointer;border-radius:4px;line-height:1}
.lb-btn:hover{background:rgba(255,255,255,.3)}
#__lb-close{position:absolute;top:14px;right:18px}
#__lb-counter{color:rgba(255,255,255,.7);font-size:.9rem;min-width:60px;text-align:center}
img[data-lb]{cursor:zoom-in!important}
</style>
<div id="__lb">
  <button class="lb-btn" id="__lb-close" onclick="__lbClose()">✕</button>
  <img id="__lb-img" src="" alt="">
  <div id="__lb-bar">
    <button class="lb-btn" onclick="__lbMove(-1)">&#8249;</button>
    <span id="__lb-counter"></span>
    <button class="lb-btn" onclick="__lbMove(1)">&#8250;</button>
  </div>
</div>
<script>
(function(){
  var imgs=[],cur=0;
  function init(){
    imgs=[...document.querySelectorAll('img')].filter(function(i){
      return i.src&&i.src.startsWith('data:image')&&i.src.length>2000;
    });
    imgs.forEach(function(img,i){
      img.setAttribute('data-lb',i);
      img.style.cursor='zoom-in';
    });

    var gallery=document.querySelector('[data-cy="mosaic-gallery-main-view"]');
    if(gallery){
      var btns=[...gallery.querySelectorAll('button')];
      btns.forEach(function(btn,i){
        if(i>=imgs.length)return;
        btn.addEventListener('click',function(e){
          e.preventDefault();
          e.stopPropagation();
          __lbOpen(i);
        });
        btn.style.cursor='zoom-in';
      });
    } else {
      imgs.forEach(function(img,i){
        img.addEventListener('click',function(){__lbOpen(i);});
      });
    }
  }
  window.__lbOpen=function(i){
    cur=i;
    document.getElementById('__lb-img').src=imgs[i].src;
    document.getElementById('__lb-counter').textContent=(i+1)+' / '+imgs.length;
    document.getElementById('__lb').classList.add('open');
  };
  window.__lbClose=function(){document.getElementById('__lb').classList.remove('open');};
  window.__lbMove=function(d){
    cur=(cur+d+imgs.length)%imgs.length;
    __lbOpen(cur);
  };
  document.getElementById('__lb').addEventListener('click',function(e){
    if(e.target===this)__lbClose();
  });
  document.addEventListener('keydown',function(e){
    if(!document.getElementById('__lb').classList.contains('open'))return;
    if(e.key==='Escape')__lbClose();
    if(e.key==='ArrowLeft')__lbMove(-1);
    if(e.key==='ArrowRight')__lbMove(1);
  });
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);
  else init();
})();
</script>`;

    html = html.replace(/<\/body>/i, lightbox + '</body>');

    return `<!DOCTYPE html>\n${html}`;
  } finally {
    await browser.close();
  }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const { id } = req.query;
  if (!id || typeof id !== 'string') {
    return res.status(400).json({ error: 'Missing listing ID' });
  }

  const useBlob = !!process.env['BLOB_READ_WRITE_TOKEN'];
  const isVercel = !!process.env['VERCEL'];
  const blobKey = `snapshots/${id}.html`;

  if (req.method === 'GET') {
    if (useBlob) {
      const { list } = await import('@vercel/blob');
      const { blobs } = await list({ prefix: `snapshots/${id}` });
      const found = blobs.find((b) => b.size > 0);
      if (found) {
        return res
          .status(200)
          .json({ exists: true, url: `/api/listings/snapshot-download?id=${id}` });
      }
      return res.status(200).json({ exists: false });
    } else {
      const htmlPath = path.join(SNAPSHOTS_DIR, `${id}.html`);
      const mhtmlPath = path.join(SNAPSHOTS_DIR, `${id}.mhtml`);
      if (existsSync(htmlPath) || existsSync(mhtmlPath)) {
        return res.status(200).json({ exists: true, url: `/api/snapshots/${id}` });
      }
      return res.status(200).json({ exists: false });
    }
  }

  if (req.method === 'POST') {
    const sql = neon(process.env['DATABASE_URL']!);

    try {
      const result = await sql`SELECT url FROM listings WHERE id = ${id}`;
      if (result.length === 0) return res.status(404).json({ error: 'Listing not found' });
      const { url } = result[0] as { url: string };

      if (isVercel || useBlob) {
        const { list, del, put } = await import('@vercel/blob');

        const { blobs: existing } = await list({ prefix: `snapshots/${id}` });
        const found = existing.find((b) => b.size > 0);
        if (found) {
          console.log(`[snapshot] existing snapshot found for ${id}, returning`);
          return res
            .status(200)
            .json({ exists: true, url: `/api/listings/snapshot-download?id=${id}` });
        }

        const html = await capturePageHTML(url);
        if (!html || html.length < 100) {
          return res.status(500).json({ error: 'Snapshot captured empty content' });
        }
        const buffer = Buffer.from(html, 'utf-8');
        console.log(`[snapshot] captured ${buffer.byteLength} bytes for ${id}`);
        const blob = await put(blobKey, buffer, {
          access: 'private',
          addRandomSuffix: false,
          contentType: 'text/html; charset=utf-8',
        });
        console.log(`[snapshot] stored at ${blob.url} (${buffer.byteLength} bytes)`);
        return res
          .status(200)
          .json({ exists: true, url: `/api/listings/snapshot-download?id=${id}` });
      } else {
        const htmlPath = path.join(SNAPSHOTS_DIR, `${id}.html`);
        if (existsSync(htmlPath)) {
          return res.status(200).json({ exists: true, url: `/api/snapshots/${id}` });
        }
        if (!existsSync(SNAPSHOTS_DIR)) mkdirSync(SNAPSHOTS_DIR, { recursive: true });
        const singleFileBin = path.join(process.cwd(), 'node_modules', '.bin', 'single-file');
        await execFileAsync(singleFileBin, [url, htmlPath, '--browser-wait-until=networkidle0'], {
          timeout: 90_000,
        });
        console.log(`[snapshot] ${htmlPath}`);
        return res.status(200).json({ exists: true, url: `/api/snapshots/${id}` });
      }
    } catch (err) {
      console.error('[snapshot]', err);
      return res.status(500).json({ error: 'Snapshot failed', detail: String(err) });
    }
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
