import type { VercelRequest, VercelResponse } from '../_types';
import { neon } from '@neondatabase/serverless';
import { existsSync, mkdirSync } from 'fs';
import { execFile } from 'child_process';
import { promisify } from 'util';
import path from 'path';

const execFileAsync = promisify(execFile);
const SNAPSHOTS_DIR = path.join(process.cwd(), 'snapshots');
const CHROMIUM_VERSION = '148.0.0';
const CHROMIUM_ARCH = process.arch === 'arm64' ? 'arm64' : 'x64';
const CHROMIUM_URL =
  process.env['CHROMIUM_DOWNLOAD_URL'] ??
  `https://github.com/Sparticuz/chromium/releases/download/v${CHROMIUM_VERSION}/chromium-v${CHROMIUM_VERSION}-pack.${CHROMIUM_ARCH}.tar`;

async function capturePageHTML(pageUrl: string): Promise<string> {
  const chromium = (await import('@sparticuz/chromium-min')).default;
  const { chromium: pw } = await import('playwright-core');

  const browser = await pw.launch({
    args: [
      ...chromium.args,
      '--disable-blink-features=AutomationControlled',
      '--disable-features=IsolateOrigins,site-per-process',
      '--flag-switches-begin',
      '--disable-site-isolation-trials',
      '--flag-switches-end',
    ],
    executablePath: await chromium.executablePath(CHROMIUM_URL),
    headless: true,
  });

  try {
    const context = await browser.newContext({
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
      viewport: { width: 1920, height: 1080 },
      locale: 'pt-PT',
      extraHTTPHeaders: {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        'Accept-Language': 'pt-PT,pt;q=0.9,en;q=0.8',
        'Accept-Encoding': 'gzip, deflate, br',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'none',
        'Sec-Fetch-User': '?1',
      },
    });

    // Hide webdriver fingerprint
    await context.addInitScript(() => {
      Object.defineProperty(navigator, 'webdriver', { get: () => false });
      Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3] });
      Object.defineProperty(navigator, 'languages', { get: () => ['pt-PT', 'pt', 'en'] });
      // @ts-ignore
      window.chrome = { runtime: {} };
    });

    const page = await context.newPage();

    // Intercept every response and cache the raw bytes + content-type
    const resourceCache = new Map<string, { body: Buffer; type: string }>();
    await page.route('**/*', async (route) => {
      try {
        const response = await route.fetch();
        const body = await response.body();
        const type = response.headers()['content-type'] ?? 'application/octet-stream';
        resourceCache.set(route.request().url(), { body, type });
        await route.fulfill({ response });
      } catch {
        await route.abort();
      }
    });

    await page.goto(pageUrl, { waitUntil: 'networkidle', timeout: 60_000 });

    // Detect bot-wall: if the page title or content looks like a block page, throw
    const blocked = await page.evaluate(() => {
      const text = document.body?.innerText ?? '';
      const title = document.title ?? '';
      return (
        text.includes('Request blocked') ||
        text.includes('Generated by cloudfront') ||
        title.toLowerCase().includes('access denied') ||
        title.toLowerCase().includes('403')
      );
    });
    if (blocked) {
      throw new Error('Bot-wall detected: the listing site blocked the headless browser');
    }

    // Strip scripts & noscript
    await page.evaluate(() => {
      document.querySelectorAll('script, noscript').forEach(el => el.remove());
    });

    let html = await page.content();

    // Inline images, CSS and fonts using captured responses (data URIs)
    for (const [url, { body, type }] of resourceCache) {
      const baseType = type.split(';')[0];
      if (!baseType.startsWith('image/') && !baseType.startsWith('text/css') && !baseType.startsWith('font/')) continue;
      const dataUri = `data:${baseType};base64,${body.toString('base64')}`;
      const escaped = url.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      html = html.replace(new RegExp(escaped, 'g'), dataUri);
    }

    return `<!DOCTYPE html>\n${html}`;
  } finally {
    await browser.close();
  }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const { id } = req.query;
  if (!id || typeof id !== 'string') {
    return res.status(400).json({ error: 'Missing listing ID' });
  }

  const useBlob = !!process.env['BLOB_READ_WRITE_TOKEN'];
  const isVercel = !!process.env['VERCEL'];
  const blobKey = `snapshots/${id}.html`;

  if (req.method === 'GET') {
    if (useBlob) {
      const { list } = await import('@vercel/blob');
      // check both new .html and old .mhtml keys
      const { blobs } = await list({ prefix: `snapshots/${id}` });
      const found = blobs.find(b => b.size > 0);
      if (found) {
        return res.status(200).json({ exists: true, url: `/api/listings/snapshot-download?id=${id}` });
      }
      return res.status(200).json({ exists: false });
    } else {
      const htmlPath = path.join(SNAPSHOTS_DIR, `${id}.html`);
      const mhtmlPath = path.join(SNAPSHOTS_DIR, `${id}.mhtml`);
      if (existsSync(htmlPath) || existsSync(mhtmlPath)) {
        return res.status(200).json({ exists: true, url: `/api/snapshots/${id}` });
      }
      return res.status(200).json({ exists: false });
    }
  }

  if (req.method === 'POST') {
    const sql = neon(process.env['DATABASE_URL']!);

    try {
      const result = await sql`SELECT url FROM listings WHERE id = ${id}`;
      if (result.length === 0) return res.status(404).json({ error: 'Listing not found' });
      const { url } = result[0] as { url: string };

      if (isVercel || useBlob) {
        // Capture FIRST — only delete old blob if new one succeeds
        const { list, del, put } = await import('@vercel/blob');

        const html = await capturePageHTML(url);
        if (!html || html.length < 100) {
          return res.status(500).json({ error: 'Snapshot captured empty content' });
        }
        const buffer = Buffer.from(html, 'utf-8');
        console.log(`[snapshot] captured ${buffer.byteLength} bytes for ${id}`);

        // Delete old blobs only after successful capture
        const { blobs: existing } = await list({ prefix: `snapshots/${id}` });
        if (existing.length > 0) {
          await del(existing.map(b => b.url));
          console.log(`[snapshot] deleted ${existing.length} old blob(s) for ${id}`);
        }

        const blob = await put(blobKey, buffer, {
          access: 'private',
          addRandomSuffix: false,
          contentType: 'text/html; charset=utf-8',
        });
        console.log(`[snapshot] stored at ${blob.url} (${buffer.byteLength} bytes)`);
        return res.status(200).json({ exists: true, url: `/api/listings/snapshot-download?id=${id}` });
      } else {
        if (!existsSync(SNAPSHOTS_DIR)) mkdirSync(SNAPSHOTS_DIR, { recursive: true });
        const snapshotPath = path.join(SNAPSHOTS_DIR, `${id}.html`);
        const singleFileBin = path.join(process.cwd(), 'node_modules', '.bin', 'single-file');
        await execFileAsync(
          singleFileBin,
          [url, snapshotPath, '--browser-wait-until=networkidle0'],
          { timeout: 90_000 }
        );
        console.log(`[snapshot] ${snapshotPath}`);
        return res.status(200).json({ exists: true, url: `/api/snapshots/${id}` });
      }
    } catch (err) {
      console.error('[snapshot]', err);
      return res.status(500).json({ error: 'Snapshot failed', detail: String(err) });
    }
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
